language: android
jdk:
 - openjdk8
 
components:
 - tools
 - platform-tools
 - build-tools-30.0.0
 - android-26
 - extra-google-google_play_services
 - extra-google-m2repository
 - extra-android-m2repository
 - sys-img-armeabi-v7a-android-17

before_install:
 - yes | sdkmanager "platforms;android-27" 
 - yes | sdkmanager "platforms;android-28"
 
before_script:
 - emulator -avd test -no-audio -no-window &
 - android-wait-for-emulator

script:
 - ./gradlew assembleDebug
