language: android
jdk: oraclejdk8

env:
  matrix:
    - ANDROID_TARGET=android-28 ANDROID_ABI=armeabi-v7a

android:
  components:
    - platform-tools
    - tools
    - tools

    - build-tools-30.0.3

    - android-29
    - android-28
    - android-22
    - sys-img-armeabi-v7a-android-28

    - extra-google-google_play_services
    - extra-google-m2repository
    - extra-android-m2repository
#    - addon-google_apis-google-19

    
before_script:
  - echo no | android create avd --force -n test -t $ANDROID_TARGET --abi $ANDROID_ABI
  - emulator -avd test -no-skin -no-audio -no-window &
  - android-wait-for-emulator
  - adb shell input keyevent 82 &

script:
  - echo "Travis branch is $TRAVIS_BRANCH"
  - echo "Travis branch is in pull request $TRAVIS_PULL+REQUEST"
  - ./gradlew connectedAndroidTest 


after_success:
  - bash <(curl -s https://codecov.io/bash)
